### ISSUE TITLE
Documenter docs not deploying

### ISSUE THREAD

**Issue by JeffFessler** [JuliaIO/GoogleDrive.jl#17]
I have checked the gh-pages branch and the Documenter docs for the `dev` branch look to be properly built there:
https://github.com/JuliaIO/GoogleDrive.jl/tree/gh-pages/dev

However, they are not deploying:
https://juliaio.github.io/GoogleDrive.jl/dev

My guess is this is an issue with the DOCUMENTER_KEY or with the docs settings for the repo.  I do not have "settings" access to the repo so I cannot check whether the keys etc. are set up properly.  (Or perhaps something is awry with `docs/make.jl`.)

@sjkelly do you have access to Settings?

**Comment by JeffFessler** [comment]
Addendum: there seems to also be some issue with deploying docs with PR #18
https://github.com/JuliaIO/GoogleDrive.jl/actions/runs/6395062371/job/17358028744?pr=18
Unsure how to diagnose.  Seems again like a permissions problem that only someone with settings access can resolve.

**Comment by sjkelly** [comment]
Seems to be working: https://juliaio.github.io/GoogleDrive.jl/

**Comment by JeffFessler** [comment]
That URL just seems to regurgitate the README.  It is not actually the material developed under `docs/`.

What we want to see is something more like this (note the tricky URL for preview here):
https://htmlpreview.github.io?https://github.com/JuliaIO/GoogleDrive.jl/blob/gh-pages/dev/index.html

**Comment by JeffFessler** [comment]
@sjkelly so I want to ask again if you have access the Settings for this repo?

**Comment by sjkelly** [comment]
@JeffFessler since we are now in an Org we can have multiple Admins. I have added you to this repo, so you should have access to the settings page now. I really appreciate you working on this!

**Comment by JeffFessler** [comment]
Thanks!  As I guessed, there were no documenter keys there.  Now there is, so hopefully the doc will deploy next time.
I will leave this open for now.

**Comment by JeffFessler** [comment]
Actually the docs deployed already so I can close this now.
